version: '3'

services:
  users:
    image: users:latest
    build: ./user
    container_name: users
    command: python3 user.py
    restart: always
    ports:
      - "8080:8080"
  rides:
    image: rides:latest
    build: ./ride
    container_name: rides
    command: python3 rides.py
    restart: always
    ports:
      - "8000:8000"