version: '3'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    image: rabbitmq:3.8.3-alpine

  master:
    image: master:latest
    build:
      context: ./master
      dockerfile: Dockerfile
    command: sh -c "sleep 15 && python master.py 1"
    links:
      - rmq
      - zoo
    depends_on:
      - rmq
      - zoo
    restart: on-failure

  slave:
    image: slave:latest
    build:
        context: ./slave
        dockerfile: Dockerfile
    command: sh -c "sleep 15 && python slave.py 0"
    links:
      - rmq
      - zoo
    depends_on:
      - rmq
      - zoo
    restart: on-failure

  dborch:
    image: dborch:latest
    build: ./dborch
    container_name: dborch
    command: sh -c "sleep 20 && python db_orch.py"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - rmq
      - zoo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock